FROM ubuntu:18.04
RUN apt-get update -y
RUN apt-get install wget -y
RUN apt-get install tar -y
RUN wget https://dl.google.com/go/go1.13.3.linux-amd64.tar.gz
RUN tar -xvf go1.13.3.linux-amd64.tar.gz
RUN mv go /usr/local
RUN export GOROOT=/usr/local/go
RUN export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
RUN export GOROOT=/usr/local/go
RUN export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
RUN export GOPATH=/home/xente/Servidor20_21/go_projects/
RUN export PATH=$PATH:/home/xente/Servidor20_21/go_projects/bin
RUN mkdir -p $GOPATH/src/github.com/revand/
WORKDIR /home/xente/Servidor20_21/go_projects/scr/github.com/revand
COPY . .
RUN go get -u github.com/gin-gonic/gin
RUN go get -u github.com/kardianos/govendor
RUN govendor sync
RUN go get -u github.com/pilu/fresh
RUN go get github.com/go-sql-driver/mysql
RUN chmod +x init.sh

EXPOSE 3000

CMD [ "./init.sh" ]